spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_4_3_7_ALTER_SYSTEM.log

set echo on

SELECT GRANTEE, PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE PRIVILEGE='ALTER SYSTEM'
AND GRANTEE NOT IN ('SYS','SYSTEM','APEX_030200','APEX_040000',
'APEX_040100','APEX_040200','DBA','EM_EXPRESS_ALL','SYSBACKUP','GSMADMIN_ROLE',
'GSM_INTERNAL','SYSDG','GSMADMIN_INTERNAL');

spool off
set echo off

exit; 
