spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_4_3_11_GRANT_ANY_ROLE.log

set echo on

SELECT GRANTEE, PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE PRIVILEGE='GRANT ANY ROLE'
AND GRANTEE NOT IN ('DBA','SYS','DATAPUMP_IMP_FULL_DATABASE','IMP_FULL_DATABASE',
'SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_USR',
'GSMADMIN_INTERNAL','DV_REALM_OWNER', 'EM_EXPRESS_ALL', 'DV_OWNER');

spool off
set echo off

exit; 
