spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_4_3_6_CREATE_PROCEDURE.log

set echo on

SELECT GRANTEE, PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE PRIVILEGE='CREATE PROCEDURE'
AND GRANTEE NOT IN ( 'DBA','DBSNMP','MDSYS','OLAPSYS','OWB$CLIENT',
'OWBSYS','RECOVERY_CATALOG_OWNER','SPATIAL_CSW_ADMIN_USR',
'SPATIAL_WFS_ADMIN_USR','SYS','APEX_030200','APEX_040000',
'APEX_040100','APEX_040200','DVF','RESOURCE','DV_REALM_RESOURCE',
'APEX_GRANTS_FOR_NEW_USERS_ROLE');

spool off
set echo off

exit; 
