spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_4_3_10_GRANT_ANY_OBJECT_PRIV.log

set echo on

SELECT GRANTEE, PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE PRIVILEGE='GRANT ANY OBJECT PRIVILEGE'
AND GRANTEE NOT IN ('DBA','SYS','IMP_FULL_DATABASE','DATAPUMP_IMP_FULL_DATABASE',
'EM_EXPRESS_ALL', 'DV_REALM_OWNER');

spool off
set echo off

exit; 
