spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_4_5_5_REV_ALL_DBA.log

set echo on

SELECT * FROM DBA_TAB_PRIVS
WHERE TABLE_NAME LIKE 'DBA_%'
and GRANTEE NOT IN ('APEX_030200','APPQOSSYS','AQ_ADMINISTRATOR_ROLE','CTXSYS',
'EXFSYS','MDSYS','OLAP_XS_ADMIN','OLAPSYS','ORDSYS','OWB$CLIENT','OWBSYS',
'SELECT_CATALOG_ROLE','WM_ADMIN_ROLE','WMSYS','XDBADMIN','LBACSYS',
'ADM_PARALLEL_EXECUTE_TASK','CISSCANROLE','APEX_040200','SYSKM','ORACLE_OCM',
'DVSYS','GSMADMIN_INTERNAL','XDB','SYSDG','SYS','AUDIT_ADMIN', 'AUDIT_VIEWER',
'CAPTURE_ADMIN', 'DBA', 'DV_ACCTMGR', 'DV_MONITOR', 'DV_SECANALYST');

spool off
set echo off

exit; 
