spool /home/oracle/shell_scr/db_harden/rep_sqls/sql_5_15_AUDIT_GRANT_ANY_OBJ_PRIV.log

set echo on

SELECT PRIVILEGE, SUCCESS, FAILURE
FROM DBA_PRIV_AUDIT_OPTS
WHERE PRIVILEGE='GRANT ANY OBJECT PRIVILEGE'
AND USER_NAME IS NULL
AND PROXY_NAME IS NULL
AND SUCCESS = 'BY ACCESS'
AND FAILURE = 'BY ACCESS';

spool off
set echo off

exit; 
